name: pong

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter_web:
  flutter_web_ui:

dev_dependencies:
  build_runner: 1.6.1
  build_web_compilers: 2.1.4

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui